import {
  Activity,
  Archive,
  BadgeCheck,
  BarChart3,
  BookOpen,
  Bot,
  Boxes,
  BrainCircuit,
  CalendarClock,
  CircleDollarSign,
  Cloud,
  Code2,
  Contact,
  CopyCheck,
  CreditCard,
  Crown,
  Database,
  DatabaseBackup,
  File,
  FileCheck2,
  FileInput,
  FileOutput,
  FileText,
  Film,
  FolderArchive,
  FolderOpen,
  GalleryHorizontalEnd,
  Gauge,
  GitBranch,
  Gavel,
  Globe,
  HandCoins,
  HardDrive,
  Image,
  Images,
  Landmark,
  Layers,
  LayoutDashboard,
  LayoutTemplate,
  Link,
  ListChecks,
  Lock,
  Mail,
  MessageSquare,
  MessagesSquare,
  MonitorUp,
  Music,
  Package,
  Palette,
  PanelTop,
  Plug,
  ReceiptText,
  RefreshCw,
  Scale,
  ScanLine,
  ScanSearch,
  ScrollText,
  Search,
  Send,
  Share2,
  ShieldAlert,
  ShieldCheck,
  ShoppingCart,
  SlidersHorizontal,
  Sparkles,
  Store,
  Tags,
  UploadCloud,
  UserCheck,
  Users,
  WandSparkles,
  Webhook,
  Workflow,
} from "lucide-react";

const feature = (title, icon, description, capabilities, maturity = "Planned") => ({
  title,
  icon,
  description,
  capabilities,
  maturity,
});

export const featureDomains = [
  {
    title: "Assets",
    icon: FolderOpen,
    description: "Ingest, organize, version, retain, and recover every asset.",
    features: [
      feature("Asset Library", FolderOpen, "The primary workspace for browsing and managing assets.", [
        "Centralized asset repository",
        "Grid and list views",
        "Configurable columns",
        "Favorites and pinned assets",
        "Recently used assets",
        "Multi-format previews",
      ], "In progress"),
      feature("Upload Center", UploadCloud, "Bring files into the library from teams and connected sources.", [
        "Drag-and-drop upload",
        "Multi-file and folder upload",
        "ZIP archive import",
        "Cloud-storage import",
        "Remote URL ingestion",
        "Upload progress and background processing",
      ]),
      feature("External Uploads", FileInput, "Collect files from clients, partners, and contributors.", [
        "Upload links",
        "Upload forms",
        "Guest submissions",
        "Required metadata",
        "Destination routing",
        "Submission notifications",
      ]),
      feature("Collections", Layers, "Curate assets without changing their library location.", [
        "Manual collections",
        "Albums and boards",
        "Smart collections",
        "Collection favorites",
        "Collection permissions",
        "Collection sharing",
      ]),
      feature("Folders & Storage", HardDrive, "Structure storage and control where source files live.", [
        "Nested folders",
        "Folder moves",
        "Storage locations",
        "Cloud buckets",
        "Cold storage",
        "Storage usage reporting",
      ]),
      feature("Duplicate Review", CopyCheck, "Find and resolve duplicate or near-duplicate assets.", [
        "Upload duplicate checks",
        "Exact duplicate detection",
        "Near-duplicate detection",
        "Visual similarity groups",
        "Merge recommendations",
        "Keep or replace decisions",
      ]),
      feature("Archive & Trash", Archive, "Retire content without immediately losing it.", [
        "Soft archive",
        "Trash",
        "Trash recovery",
        "Bulk restore",
        "Permanent deletion controls",
        "Archive search",
      ]),
      feature("Asset Requests", Mail, "Request missing creative work and track delivery.", [
        "Request forms",
        "Assignees",
        "Due dates",
        "Reference assets",
        "Submission status",
        "Request notifications",
      ]),
    ],
  },
  {
    title: "Media",
    icon: Image,
    description: "Preview, inspect, and transform every supported media type.",
    features: [
      feature("Images", Image, "Manage photography, graphics, illustrations, and raster media.", [
        "Image preview",
        "RAW image support",
        "Color profile metadata",
        "Dimensions and orientation",
        "Focal points",
        "High-resolution zoom",
      ]),
      feature("Video & Transcripts", Film, "Manage video masters, clips, subtitles, and transcripts.", [
        "Streaming video preview",
        "Video thumbnails",
        "Storyboard view",
        "Speech-to-text",
        "Captions and subtitles",
        "Frame-specific comments",
      ]),
      feature("Audio", Music, "Manage audio recordings, music, and spoken media.", [
        "Audio playback",
        "Waveform preview",
        "Audio metadata",
        "Speech-to-text",
        "Audio clipping",
        "Transcript search",
      ]),
      feature("Documents & OCR", FileText, "Preview and search office documents, PDFs, and presentations.", [
        "PDF preview",
        "Document preview",
        "Presentation preview",
        "Page thumbnails",
        "OCR extraction",
        "Page extraction",
      ]),
      feature("Design & Raw Files", File, "Store editable design sources and production originals.", [
        "PSD and Illustrator previews",
        "Figma and Sketch references",
        "Camera RAW files",
        "Font previews",
        "Source and export relationships",
        "Design metadata",
      ]),
      feature("3D & Immersive", Boxes, "Review 3D models and immersive media.", [
        "Interactive 3D preview",
        "Rotate and zoom",
        "3D thumbnails",
        "Model metadata",
        "AR preview",
        "Immersive media support",
      ]),
      feature("Image Editing", WandSparkles, "Create delivery-ready image variations.", [
        "Crop, resize, and rotate",
        "Color adjustments",
        "Annotations",
        "Background removal",
        "Watermarks and overlays",
        "Smart crop",
      ]),
      feature("Video Processing", RefreshCw, "Generate optimized video variants.", [
        "Video trimming",
        "Clip creation",
        "Transcoding",
        "Poster frames",
        "Adaptive streaming",
        "Format conversion",
      ]),
      feature("Renditions & Formats", FileOutput, "Generate reusable output formats from source assets.", [
        "Automated renditions",
        "Preset downloads",
        "Format conversion",
        "Compression",
        "Quality optimization",
        "Responsive image sets",
      ]),
    ],
  },
  {
    title: "Collaboration",
    icon: MessagesSquare,
    description: "Coordinate review, feedback, sharing, and team activity.",
    features: [
      feature("Shared Links", Share2, "Share individual assets and curated sets outside the workspace.", [
        "Asset and collection links",
        "Public and private links",
        "Password protection",
        "Link expiration",
        "View-only access",
        "Download controls",
      ]),
      feature("Approvals", ListChecks, "Move assets from draft to approved with clear decisions.", [
        "Review requests",
        "Approve and reject",
        "Change requests",
        "Approval history",
        "Approved-version locking",
        "External approval",
      ]),
      feature("Team", Users, "Manage workspace members and collaborators.", [
        "Members and guests",
        "Teams and groups",
        "Invitations",
        "Contributor access",
        "External reviewers",
        "Member activity",
      ]),
    ],
  },
  {
    title: "Workflows",
    icon: Workflow,
    description: "Automate repeatable content operations and approvals.",
    features: [
      feature("Workflow Builder", Workflow, "Model asset lifecycle processes without code.", [
        "Custom stages",
        "Status transitions",
        "Entry and exit rules",
        "Assignments",
        "Due dates",
        "Reusable workflow templates",
      ]),
      feature("Publishing Workflows", Send, "Control when approved assets reach external channels.", [
        "Publish approvals",
        "Scheduled publishing",
        "Channel selection",
        "Unpublish actions",
        "Distribution status",
        "Publishing history",
      ]),
      feature("Import & Export Jobs", RefreshCw, "Run repeatable bulk data and asset transfers.", [
        "Scheduled imports",
        "Scheduled exports",
        "Cloud synchronization",
        "Metadata mapping",
        "Job history",
        "Failure retry",
      ]),
    ],
  },
  {
    title: "Delivery",
    icon: Cloud,
    description: "Publish optimized assets to websites, apps, and channels.",
    features: [
      feature("CDN Delivery", Cloud, "Serve optimized media globally from edge locations.", [
        "Global CDN",
        "Edge caching",
        "Cache invalidation",
        "Custom delivery domains",
        "Origin protection",
        "Delivery status",
      ]),
      feature("Dynamic Images", Image, "Transform images at delivery time.", [
        "URL-based resize",
        "URL-based crop",
        "Format negotiation",
        "Quality optimization",
        "Device-aware delivery",
        "Responsive breakpoints",
      ]),
      feature("Video Delivery", Film, "Stream optimized video experiences.", [
        "Adaptive streaming",
        "Video CDN",
        "Player configuration",
        "Poster images",
        "Captions",
        "Signed streams",
      ]),
      feature("Embeds & Headless", Link, "Use assets in applications without coupling to the DAM UI.", [
        "Embed codes",
        "Stable asset URLs",
        "Headless asset queries",
        "Version-aware embeds",
        "Delivery SDKs",
        "Composable architecture",
      ]),
      feature("Channel Publishing", MonitorUp, "Send assets into connected business systems.", [
        "CMS publishing",
        "PIM publishing",
        "Ecommerce publishing",
        "Social publishing",
        "Marketing automation",
        "Scheduled exports",
      ]),
      feature("Delivery Analytics", BarChart3, "Measure how assets perform after distribution.", [
        "Delivery requests",
        "Bandwidth usage",
        "Cache-hit ratio",
        "Top delivered assets",
        "Geographic delivery",
        "Transformation usage",
      ]),
    ],
  },
  {
    title: "Galleries",
    icon: Store,
    description: "Publish showcase galleries and transactional media stores.",
    features: [
      feature("Gallery Builder", GalleryHorizontalEnd, "Turn a collection into a hosted gallery.", [
        "Collection publishing",
        "Gallery layouts",
        "Theme controls",
        "Custom navigation",
        "Preview and publish",
        "Gallery duplication",
      ]),
      feature("Showcase Galleries", Images, "Present media without requiring a transaction.", [
        "Public showcases",
        "Private showcases",
        "Password protection",
        "Favorites and proofing",
        "Download requests",
        "Visitor analytics",
      ]),
      feature("Gallery Domains", Globe, "Host galleries on branded domains.", [
        "Custom domains",
        "Subdomains",
        "SSL",
        "SEO metadata",
        "Social previews",
        "Domain verification",
      ]),
      feature("Storefront", Store, "Enable shopping and licensing from gallery pages.", [
        "Product pages",
        "Shopping cart",
        "Checkout",
        "Customer accounts",
        "Discount codes",
        "Store policies",
      ]),
      feature("Digital Downloads", FileOutput, "Sell and automatically deliver digital files.", [
        "Single-asset sales",
        "Asset bundles",
        "Rendition selection",
        "Automatic fulfillment",
        "Download limits",
        "Delivery history",
      ]),
      feature("Products & Pricing", Package, "Configure what galleries sell and at what price.", [
        "Digital products",
        "License products",
        "Price sheets",
        "Per-asset pricing",
        "Bundles and packages",
        "Regional currencies",
      ]),
      feature("Cart & Checkout", ShoppingCart, "Convert gallery visitors into customers.", [
        "Guest checkout",
        "Account checkout",
        "Payment collection",
        "Taxes",
        "Terms acceptance",
        "Order confirmation",
      ]),
      feature("Orders & Invoices", ReceiptText, "Operate the financial side of gallery sales.", [
        "Order management",
        "Invoices and receipts",
        "Refunds",
        "Tax records",
        "Order status",
        "Exportable reports",
      ]),
      feature("Customers", Contact, "Keep a record of gallery buyers and licensees.", [
        "Customer profiles",
        "Organizations",
        "Purchase history",
        "Download history",
        "License history",
        "Customer notes",
      ]),
    ],
  },
  {
    title: "Memberships",
    icon: CreditCard,
    description: "Define tiers, manage recurring subscriptions, restrict content, and sell membership access on galleries.",
    features: [
      feature("Membership Tiers", Layers, "Define access levels, subscription pricing, and download limits for members.", [
        "Multi-tier plan builder",
        "Custom billing intervals (monthly/annual)",
        "Free and paid tiers",
        "Tier-specific download quotas",
        "Grace period settings",
        "Trial period configurations",
      ]),
      feature("Access Control", Lock, "Gate assets, collections, and galleries based on member tiers.", [
        "Folder and collection locks",
        "Gallery paywalls and login gates",
        "Watermark bypass permissions",
        "High-resolution download restrictions",
        "Preview-only access constraints",
        "Metadata visibility controls",
      ]),
      feature("Member Registry", Users, "Track member profiles, active subscriptions, and account statuses.", [
        "Centralized member directory",
        "Active subscription tracking",
        "Member login history",
        "Manual tier assignments",
        "Account suspension & reactivation",
        "Download & view activity logs",
      ]),
      feature("Recurring Billing", CreditCard, "Manage renewals, invoices, payment methods, and failed transactions.", [
        "Stripe and PayPal integrations",
        "Auto-renewal processing",
        "Failed payment retries (dunning)",
        "Member billing portal",
        "Invoice generation & receipts",
        "Refund management",
      ]),
      feature("Promo Codes & Perks", Tags, "Offer signup discounts, free trials, and exclusive store coupons to members.", [
        "Subscription discount codes",
        "Storefront purchase discounts",
        "Affiliate referral tracking",
        "Exclusive asset downloads",
        "Limited-time promo builders",
        "Bulk coupon generation",
      ]),
      feature("Gallery Integrations", Store, "Connect memberships directly to showcase galleries and asset storefronts.", [
        "Add membership login to galleries",
        "Member-only pricing on storefronts",
        "Interactive paywalls on galleries",
        "Custom signup forms in galleries",
        "Tier-restricted asset libraries",
        "Bespoke member welcome banners",
      ]),
    ],
  },
  {
    title: "Creator",
    icon: Crown,
    description: "Patreon-style memberships plus OnlyFans-style PPV, paid DMs, tips, and payouts.",
    features: [
      feature("Membership Tiers", Layers, "Recurring tiers with monthly/annual intervals, free funnel entry, and perks.", [
        "Multi-tier plan builder",
        "Monthly and annual intervals",
        "Free and paid tiers",
        "Trial period configurations",
        "Tier perks",
        "Position ordering",
      ], "In progress"),
      feature("Members", Users, "Fan registry with lifetime value, status, and activity.", [
        "Centralized member directory",
        "Lifetime spend tracking",
        "Trialing and past-due states",
        "Account suspension & reactivation",
        "Last-seen activity",
        "Manual member entry",
      ], "In progress"),
      feature("Subscriptions", RefreshCw, "Recurring billing records linking members to tiers.", [
        "Member-to-tier attachment",
        "Trialing and renewal periods",
        "Past-due dunning queue",
        "Cancel at period end",
        "Churn tracking",
        "Billing history",
      ], "In progress"),
      feature("Pay-Per-View", Lock, "Locked posts with free teasers and paid unlocks.", [
        "Teaser text and preview",
        "Per-post unlock pricing",
        "Publish and archive flow",
        "Unlock counts",
        "Per-post revenue",
        "PPV unlock ledger",
      ], "In progress"),
      feature("Paid Messages", Send, "Mass PPV drops and 1:1 locked DMs with unlock tracking.", [
        "Mass DM broadcasts",
        "1:1 locked messages",
        "Unlock pricing per message",
        "Locked value pipeline",
        "Conversion tracking",
        "Unlock reconciliation",
      ], "In progress"),
      feature("Tips", HandCoins, "Gratitude revenue on posts, messages, streams, and profiles.", [
        "Tips by target type",
        "Tip notes",
        "Succeeded and refunded states",
        "Average tip analytics",
        "Top-tipper signals",
        "Read-only checkout ledger",
      ], "In progress"),
      feature("Payouts", Landmark, "Settle gross revenue minus fees into net payouts.", [
        "Gross, fees, and net per period",
        "Pending and processing queue",
        "Paid confirmation",
        "Destination accounts",
        "Failed payout retry",
        "Revenue reconciliation",
      ], "In progress"),
      feature("Promo Codes & Perks", Tags, "Discounts, trials, and gifted months for acquisition.", [
        "Discount codes",
        "Trial builders",
        "Free-month gifting",
        "Redemption tracking",
        "Pause and resume",
        "Duration windows",
      ], "In progress"),
    ],
  },
  {
    title: "Licensing",
    icon: BadgeCheck,
    description: "Manage inbound rights and licenses issued to customers.",
    features: [
      feature("Rights Inventory", Scale, "Record the rights the organization owns or controls.", [
        "Rights holders",
        "Acquired rights",
        "Ownership shares",
        "Territories",
        "Channels and media",
        "Rights windows",
      ]),
      feature("License Templates", ScrollText, "Define reusable outbound grants and pricing rules.", [
        "Fixed license templates",
        "Usage types",
        "Territories",
        "Channels",
        "Durations",
        "Restrictions",
      ]),
      feature("License Pricing", CircleDollarSign, "Calculate prices from the requested usage scope.", [
        "Base prices",
        "Territory multipliers",
        "Duration multipliers",
        "Channel multipliers",
        "Exclusivity premiums",
        "Custom quote requests",
      ]),
      feature("Issued Licenses", BadgeCheck, "Track each grant issued to a buyer or licensee.", [
        "Licensee records",
        "Licensed assets and versions",
        "Grant scope",
        "Issue and start dates",
        "License status",
        "License certificate",
      ]),
      feature("Expirations & Renewals", CalendarClock, "Manage customer-specific license windows.", [
        "Expiration dates",
        "Renewal options",
        "Renewal reminders",
        "Grace periods",
        "Termination",
        "Expired-license actions",
      ]),
      feature("Revenue & Royalties", CircleDollarSign, "Connect licenses to income and rightsholder obligations.", [
        "Asset-level income",
        "License revenue",
        "Royalty rates",
        "Revenue shares",
        "Minimum guarantees",
        "Recoupment",
      ]),
    ],
  },
  {
    title: "Governance",
    icon: ShieldCheck,
    description: "Control access, retention, compliance, and defensible records.",
    features: [
      feature("Permissions", Lock, "Control access from workspace to individual assets.", [
        "Workspace roles",
        "Folder permissions",
        "Collection permissions",
        "Asset permissions",
        "Portal permissions",
        "Field-level permissions",
      ]),
      feature("Identity & Provisioning", UserCheck, "Connect enterprise identity and automate membership.", [
        "Single sign-on",
        "SAML",
        "SCIM",
        "Multi-factor authentication",
        "Domain controls",
        "Automatic deprovisioning",
      ]),
      feature("Retention Policies", DatabaseBackup, "Apply lifecycle rules to records and files.", [
        "Retention schedules",
        "Auto-archive",
        "Auto-delete",
        "Policy exceptions",
        "Disposition review",
        "Retention reporting",
      ]),
      feature("Legal Holds", Gavel, "Preserve records subject to legal or regulatory review.", [
        "Hold creation",
        "Asset preservation",
        "Custodian records",
        "Hold notifications",
        "Release from hold",
        "Hold audit history",
      ]),
    ],
  },
  {
    title: "Platform",
    icon: Code2,
    description: "Integrate the DAM with creative, business, and developer ecosystems.",
    features: [
      feature("Integrations", Plug, "Connect common creative and business applications.", [
        "Creative tools",
        "Cloud storage",
        "Productivity tools",
        "Project management",
        "Marketing platforms",
        "Social platforms",
      ]),
      feature("API", Code2, "Expose assets and operations to custom applications.", [
        "REST API",
        "GraphQL API",
        "Asset CRUD",
        "Search API",
        "Delivery API",
        "Admin API",
      ]),
      feature("SDKs", Package, "Provide supported libraries for application teams.", [
        "JavaScript SDK",
        "TypeScript types",
        "Server SDKs",
        "Upload SDKs",
        "Delivery SDKs",
        "Examples and starters",
      ]),
      feature("Webhooks", Webhook, "Notify external systems when DAM events occur.", [
        "Asset events",
        "Workflow events",
        "Rights events",
        "Order events",
        "Signature verification",
        "Retry and delivery logs",
      ]),
      feature("Data Import & Export", FileOutput, "Move metadata and records in standard formats.", [
        "CSV import and export",
        "JSON export",
        "Bulk asset export",
        "Metadata mappings",
        "Migration tools",
        "Scheduled data feeds",
      ]),
    ],
  },
  {
    title: "Analytics",
    icon: BarChart3,
    description: "Measure adoption, content performance, delivery, and revenue.",
    features: [
      feature("Asset Analytics", BarChart3, "Understand how individual assets are found and used.", [
        "Views",
        "Downloads",
        "Shares",
        "Embeds",
        "Usage locations",
        "Performance over time",
      ]),
      feature("Search Analytics", Search, "Improve findability by studying search behavior.", [
        "Top queries",
        "Failed searches",
        "Zero-result queries",
        "Filter usage",
        "Search conversion",
        "Search trends",
      ]),
      feature("Portal Analytics", Globe, "Measure external portal engagement.", [
        "Portal visitors",
        "Popular assets",
        "Downloads",
        "Visitor geography",
        "Referrers",
        "Portal conversion",
      ]),
      feature("Library Health", Gauge, "Monitor quality and operational cleanliness.", [
        "Metadata completeness",
        "Duplicate volume",
        "Expired rights",
        "Unapproved assets",
        "Unused assets",
        "Archive candidates",
      ]),
      feature("Storage & Usage", HardDrive, "Track consumption against plan limits.", [
        "Storage usage",
        "Bandwidth usage",
        "Transformation usage",
        "AI credits",
        "Active users",
        "Limit alerts",
      ]),
      feature("Commerce Analytics", CircleDollarSign, "Track gallery and storefront performance.", [
        "Revenue",
        "Orders",
        "Conversion",
        "Average order value",
        "Product performance",
        "Refunds",
      ]),
      feature("License Analytics", Scale, "Measure the value and risk of issued rights.", [
        "License revenue",
        "Active licenses",
        "Upcoming expirations",
        "Renewal rate",
        "Territory mix",
        "Asset-level licensing income",
      ]),
      feature("Reports & Exports", FileOutput, "Create recurring stakeholder-ready reports.", [
        "Custom dashboards",
        "Scheduled reports",
        "CSV exports",
        "PDF exports",
        "Saved report filters",
        "Report sharing",
      ]),
    ],
  },
];

export const featureNav = featureDomains.map((domain) => ({
  title: domain.title,
  icon: domain.icon,
  description: domain.description,
  subItems: domain.features,
}));

export const featureItems = featureDomains.flatMap((domain) =>
  domain.features.map((item) => ({
    ...item,
    domain: domain.title,
    domainIcon: domain.icon,
  })),
);

export const featureItemsByTitle = new Map(
  featureItems.map((item) => [item.title, item]),
);

export const overviewNavItem = {
  title: "Overview",
  icon: LayoutDashboard,
};
