import {
  Activity,
  Archive,
  BadgeCheck,
  BarChart3,
  BookOpen,
  Bot,
  Boxes,
  BrainCircuit,
  CalendarClock,
  CircleDollarSign,
  Cloud,
  Code2,
  Contact,
  CopyCheck,
  Database,
  DatabaseBackup,
  File,
  FileCheck2,
  FileInput,
  FileOutput,
  FileText,
  Film,
  FolderArchive,
  FolderOpen,
  GalleryHorizontalEnd,
  Gauge,
  GitBranch,
  Gavel,
  Globe,
  HardDrive,
  History,
  Image,
  Images,
  Landmark,
  Layers,
  LayoutDashboard,
  LayoutTemplate,
  Link,
  ListChecks,
  Lock,
  Mail,
  MessageSquare,
  MessagesSquare,
  MonitorUp,
  Music,
  Package,
  Palette,
  PanelTop,
  Plug,
  ReceiptText,
  RefreshCw,
  Repeat2,
  Scale,
  ScanLine,
  ScanSearch,
  ScrollText,
  Search,
  Send,
  Share2,
  ShieldAlert,
  ShieldCheck,
  ShoppingCart,
  SlidersHorizontal,
  Sparkles,
  Store,
  Tags,
  UploadCloud,
  UserCheck,
  Users,
  WandSparkles,
  Webhook,
  Workflow,
} from "lucide-react";

const feature = (title, icon, description, capabilities, maturity = "Planned") => ({
  title,
  icon,
  description,
  capabilities,
  maturity,
});

export const featureDomains = [
  {
    title: "Assets",
    icon: FolderOpen,
    description: "Ingest, organize, version, retain, and recover every asset.",
    features: [
      feature("Asset Library", FolderOpen, "The primary workspace for browsing and managing assets.", [
        "Centralized asset repository",
        "Grid and list views",
        "Configurable columns",
        "Favorites and pinned assets",
        "Recently used assets",
        "Multi-format previews",
      ], "In progress"),
      feature("Upload Center", UploadCloud, "Bring files into the library from teams and connected sources.", [
        "Drag-and-drop upload",
        "Multi-file and folder upload",
        "ZIP archive import",
        "Cloud-storage import",
        "Remote URL ingestion",
        "Upload progress and background processing",
      ]),
      feature("External Uploads", FileInput, "Collect files from clients, partners, and contributors.", [
        "Upload links",
        "Upload forms",
        "Guest submissions",
        "Required metadata",
        "Destination routing",
        "Submission notifications",
      ]),
      feature("Collections", Layers, "Curate assets without changing their library location.", [
        "Manual collections",
        "Albums and boards",
        "Smart collections",
        "Collection favorites",
        "Collection permissions",
        "Collection sharing",
      ]),
      feature("Folders & Storage", HardDrive, "Structure storage and control where source files live.", [
        "Nested folders",
        "Folder moves",
        "Storage locations",
        "Cloud buckets",
        "Cold storage",
        "Storage usage reporting",
      ]),
      feature("Asset Relationships", Repeat2, "Connect originals, derivatives, variants, and related records.", [
        "Parent and child assets",
        "Derived asset tracking",
        "Source-file tracking",
        "Asset bundles",
        "Campaign relationships",
        "Product relationships",
      ]),
      feature("Version Control", History, "Keep an inspectable history of every asset revision.", [
        "Version history",
        "Replace-file workflow",
        "Version labels",
        "Version comparison",
        "Restore previous version",
        "Approved current version",
      ]),
      feature("Duplicate Review", CopyCheck, "Find and resolve duplicate or near-duplicate assets.", [
        "Upload duplicate checks",
        "Exact duplicate detection",
        "Near-duplicate detection",
        "Visual similarity groups",
        "Merge recommendations",
        "Keep or replace decisions",
      ]),
      feature("Archive & Trash", Archive, "Retire content without immediately losing it.", [
        "Soft archive",
        "Trash",
        "Trash recovery",
        "Bulk restore",
        "Permanent deletion controls",
        "Archive search",
      ]),
      feature("Asset Requests", Mail, "Request missing creative work and track delivery.", [
        "Request forms",
        "Assignees",
        "Due dates",
        "Reference assets",
        "Submission status",
        "Request notifications",
      ]),
    ],
  },
  {
    title: "Metadata & Search",
    icon: Search,
    description: "Describe assets consistently and retrieve them quickly.",
    features: [
      feature("Metadata Fields", SlidersHorizontal, "Define structured fields for each asset type.", [
        "Text, number, and date fields",
        "Single and multi-select fields",
        "Boolean fields",
        "Relationship fields",
        "Required fields",
        "Field-level permissions",
      ]),
      feature("Tags & Keywords", Tags, "Apply flexible labels alongside structured metadata.", [
        "Tags and keywords",
        "Hierarchical tags",
        "Controlled vocabularies",
        "Tag suggestions",
        "Bulk tagging",
        "Tag merging",
      ]),
      feature("Taxonomies", GitBranch, "Govern category trees and enterprise vocabularies.", [
        "Nested categories",
        "Taxonomy schemas",
        "Allowed values",
        "Taxonomy inheritance",
        "Term aliases",
        "Taxonomy administration",
      ]),
      feature("Metadata Templates", LayoutTemplate, "Reuse metadata structures for common upload types.", [
        "Metadata presets",
        "Upload templates",
        "Default values",
        "Required-field sets",
        "Asset-type templates",
        "Bulk template application",
      ]),
      feature("Embedded Metadata", FileText, "Read and write metadata carried inside media files.", [
        "EXIF extraction",
        "IPTC extraction",
        "XMP extraction",
        "Video metadata",
        "Audio metadata",
        "Metadata import and export",
      ]),
      feature("Advanced Search", Search, "Search filenames, descriptions, metadata, and content.", [
        "Full-text search",
        "Metadata search",
        "Tag search",
        "Search within results",
        "Exact and fuzzy matching",
        "Result ranking",
      ]),
      feature("Filters & Facets", SlidersHorizontal, "Narrow results using composable filters.", [
        "File-type filters",
        "Owner and date filters",
        "Status filters",
        "Rights-status filters",
        "Dimension and duration filters",
        "AND and OR filter logic",
      ]),
      feature("Saved Searches", BadgeCheck, "Save reusable queries and dynamic result sets.", [
        "Personal saved searches",
        "Shared saved searches",
        "Smart collections from queries",
        "Search alerts",
        "Pinned searches",
        "Search subscriptions",
      ]),
      feature("Content Search", ScanSearch, "Find text and speech contained inside assets.", [
        "OCR text search",
        "Document-content search",
        "Video transcript search",
        "Audio transcript search",
        "Caption search",
        "Time-coded search results",
      ]),
    ],
  },
  {
    title: "Media",
    icon: Image,
    description: "Preview, inspect, and transform every supported media type.",
    features: [
      feature("Images", Image, "Manage photography, graphics, illustrations, and raster media.", [
        "Image preview",
        "RAW image support",
        "Color profile metadata",
        "Dimensions and orientation",
        "Focal points",
        "High-resolution zoom",
      ]),
      feature("Video & Transcripts", Film, "Manage video masters, clips, subtitles, and transcripts.", [
        "Streaming video preview",
        "Video thumbnails",
        "Storyboard view",
        "Speech-to-text",
        "Captions and subtitles",
        "Frame-specific comments",
      ]),
      feature("Audio", Music, "Manage audio recordings, music, and spoken media.", [
        "Audio playback",
        "Waveform preview",
        "Audio metadata",
        "Speech-to-text",
        "Audio clipping",
        "Transcript search",
      ]),
      feature("Documents & OCR", FileText, "Preview and search office documents, PDFs, and presentations.", [
        "PDF preview",
        "Document preview",
        "Presentation preview",
        "Page thumbnails",
        "OCR extraction",
        "Page extraction",
      ]),
      feature("Design & Raw Files", File, "Store editable design sources and production originals.", [
        "PSD and Illustrator previews",
        "Figma and Sketch references",
        "Camera RAW files",
        "Font previews",
        "Source and export relationships",
        "Design metadata",
      ]),
      feature("3D & Immersive", Boxes, "Review 3D models and immersive media.", [
        "Interactive 3D preview",
        "Rotate and zoom",
        "3D thumbnails",
        "Model metadata",
        "AR preview",
        "Immersive media support",
      ]),
      feature("Image Editing", WandSparkles, "Create delivery-ready image variations.", [
        "Crop, resize, and rotate",
        "Color adjustments",
        "Annotations",
        "Background removal",
        "Watermarks and overlays",
        "Smart crop",
      ]),
      feature("Video Processing", RefreshCw, "Generate optimized video variants.", [
        "Video trimming",
        "Clip creation",
        "Transcoding",
        "Poster frames",
        "Adaptive streaming",
        "Format conversion",
      ]),
      feature("Renditions & Formats", FileOutput, "Generate reusable output formats from source assets.", [
        "Automated renditions",
        "Preset downloads",
        "Format conversion",
        "Compression",
        "Quality optimization",
        "Responsive image sets",
      ]),
    ],
  },
  {
    title: "Collaboration",
    icon: MessagesSquare,
    description: "Coordinate review, feedback, sharing, and team activity.",
    features: [
      feature("Shared Links", Share2, "Share individual assets and curated sets outside the workspace.", [
        "Asset and collection links",
        "Public and private links",
        "Password protection",
        "Link expiration",
        "View-only access",
        "Download controls",
      ]),
      feature("Comments & Proofing", MessageSquare, "Review creative work directly on the asset.", [
        "Asset comments",
        "Visual annotations",
        "Document annotations",
        "Video frame comments",
        "Mentions and reactions",
        "Resolved feedback",
      ]),
      feature("Approvals", ListChecks, "Move assets from draft to approved with clear decisions.", [
        "Review requests",
        "Approve and reject",
        "Change requests",
        "Approval history",
        "Approved-version locking",
        "External approval",
      ]),
      feature("Team", Users, "Manage workspace members and collaborators.", [
        "Members and guests",
        "Teams and groups",
        "Invitations",
        "Contributor access",
        "External reviewers",
        "Member activity",
      ]),
      feature("Assignments", UserCheck, "Give asset tasks clear owners and deadlines.", [
        "Assignees",
        "Due dates",
        "Task status",
        "Review ownership",
        "Escalations",
        "Work queues",
      ]),
      feature("Notifications", Activity, "Keep participants informed about relevant changes.", [
        "In-app notifications",
        "Email notifications",
        "Mention alerts",
        "Approval alerts",
        "Expiry alerts",
        "Notification preferences",
      ]),
      feature("Activity Log", Activity, "Inspect what happened across assets and projects.", [
        "Asset activity feed",
        "Change history",
        "Upload history",
        "Download history",
        "Share history",
        "User activity",
      ]),
    ],
  },
  {
    title: "Brand",
    icon: Palette,
    description: "Keep distributed content aligned with brand standards.",
    features: [
      feature("Brand Guidelines", BookOpen, "Publish the rules that govern brand usage.", [
        "Logo guidance",
        "Color guidance",
        "Typography guidance",
        "Photography guidance",
        "Voice and tone",
        "Do and do-not examples",
      ]),
      feature("Brand Libraries", Images, "Organize approved brand foundations.", [
        "Logo libraries",
        "Color libraries",
        "Font libraries",
        "Icon libraries",
        "Approved asset indicators",
        "Deprecated asset warnings",
      ]),
      feature("Brand Templates", LayoutTemplate, "Let teams create content within controlled layouts.", [
        "Digital templates",
        "Print templates",
        "Social templates",
        "Presentation templates",
        "Marketing collateral",
        "Template permissions",
      ]),
      feature("Template Editor", Palette, "Edit approved template regions without breaking the brand.", [
        "Locked elements",
        "Editable regions",
        "Text and image replacement",
        "Data-driven variants",
        "Approval before export",
        "Multi-format export",
      ]),
      feature("Brand Portals", Globe, "Distribute approved assets and guidance to wider audiences.", [
        "Public and private portals",
        "Portal navigation",
        "Portal search",
        "Custom branding",
        "Custom domains",
        "Partner and press portals",
      ]),
      feature("Brand Compliance", ShieldCheck, "Detect and prevent off-brand asset usage.", [
        "Approved-use rules",
        "Brand checks",
        "Deprecated asset blocks",
        "Template controls",
        "Compliance review",
        "Usage warnings",
      ]),
    ],
  },
  {
    title: "Workflows",
    icon: Workflow,
    description: "Automate repeatable content operations and approvals.",
    features: [
      feature("Approval Workflows", GitBranch, "Configure simple or complex approval paths.", [
        "Sequential approvals",
        "Parallel approvals",
        "Conditional approvals",
        "Multi-stage review",
        "Approval groups",
        "Escalations",
      ]),
      feature("Workflow Builder", Workflow, "Model asset lifecycle processes without code.", [
        "Custom stages",
        "Status transitions",
        "Entry and exit rules",
        "Assignments",
        "Due dates",
        "Reusable workflow templates",
      ]),
      feature("Rules & Automations", Sparkles, "Run actions when assets meet defined conditions.", [
        "Trigger-based actions",
        "Auto-tagging",
        "Auto-routing",
        "Auto-conversion",
        "Scheduled automation",
        "Conditional logic",
      ]),
      feature("Publishing Workflows", Send, "Control when approved assets reach external channels.", [
        "Publish approvals",
        "Scheduled publishing",
        "Channel selection",
        "Unpublish actions",
        "Distribution status",
        "Publishing history",
      ]),
      feature("Import & Export Jobs", RefreshCw, "Run repeatable bulk data and asset transfers.", [
        "Scheduled imports",
        "Scheduled exports",
        "Cloud synchronization",
        "Metadata mapping",
        "Job history",
        "Failure retry",
      ]),
      feature("Moderation", ShieldAlert, "Review uploaded and generated content for policy violations.", [
        "Automated moderation",
        "Manual review queues",
        "Policy labels",
        "Rejected-content handling",
        "Appeals",
        "Moderation history",
      ]),
    ],
  },
  {
    title: "Delivery",
    icon: Cloud,
    description: "Publish optimized assets to websites, apps, and channels.",
    features: [
      feature("CDN Delivery", Cloud, "Serve optimized media globally from edge locations.", [
        "Global CDN",
        "Edge caching",
        "Cache invalidation",
        "Custom delivery domains",
        "Origin protection",
        "Delivery status",
      ]),
      feature("Dynamic Images", Image, "Transform images at delivery time.", [
        "URL-based resize",
        "URL-based crop",
        "Format negotiation",
        "Quality optimization",
        "Device-aware delivery",
        "Responsive breakpoints",
      ]),
      feature("Video Delivery", Film, "Stream optimized video experiences.", [
        "Adaptive streaming",
        "Video CDN",
        "Player configuration",
        "Poster images",
        "Captions",
        "Signed streams",
      ]),
      feature("Secure Delivery", Lock, "Protect private assets and licensed downloads.", [
        "Signed URLs",
        "Expiring URLs",
        "Authenticated delivery",
        "IP and domain restrictions",
        "Download limits",
        "Revocation",
      ]),
      feature("Embeds & Headless", Link, "Use assets in applications without coupling to the DAM UI.", [
        "Embed codes",
        "Stable asset URLs",
        "Headless asset queries",
        "Version-aware embeds",
        "Delivery SDKs",
        "Composable architecture",
      ]),
      feature("Channel Publishing", MonitorUp, "Send assets into connected business systems.", [
        "CMS publishing",
        "PIM publishing",
        "Ecommerce publishing",
        "Social publishing",
        "Marketing automation",
        "Scheduled exports",
      ]),
      feature("Delivery Analytics", BarChart3, "Measure how assets perform after distribution.", [
        "Delivery requests",
        "Bandwidth usage",
        "Cache-hit ratio",
        "Top delivered assets",
        "Geographic delivery",
        "Transformation usage",
      ]),
    ],
  },
  {
    title: "Galleries",
    icon: Store,
    description: "Publish showcase galleries and transactional media stores.",
    features: [
      feature("Gallery Builder", GalleryHorizontalEnd, "Turn a collection into a hosted gallery.", [
        "Collection publishing",
        "Gallery layouts",
        "Theme controls",
        "Custom navigation",
        "Preview and publish",
        "Gallery duplication",
      ]),
      feature("Showcase Galleries", Images, "Present media without requiring a transaction.", [
        "Public showcases",
        "Private showcases",
        "Password protection",
        "Favorites and proofing",
        "Download requests",
        "Visitor analytics",
      ]),
      feature("Gallery Domains", Globe, "Host galleries on branded domains.", [
        "Custom domains",
        "Subdomains",
        "SSL",
        "SEO metadata",
        "Social previews",
        "Domain verification",
      ]),
      feature("Storefront", Store, "Enable shopping and licensing from gallery pages.", [
        "Product pages",
        "Shopping cart",
        "Checkout",
        "Customer accounts",
        "Discount codes",
        "Store policies",
      ]),
      feature("Digital Downloads", FileOutput, "Sell and automatically deliver digital files.", [
        "Single-asset sales",
        "Asset bundles",
        "Rendition selection",
        "Automatic fulfillment",
        "Download limits",
        "Delivery history",
      ]),
      feature("Products & Pricing", Package, "Configure what galleries sell and at what price.", [
        "Digital products",
        "License products",
        "Price sheets",
        "Per-asset pricing",
        "Bundles and packages",
        "Regional currencies",
      ]),
      feature("Cart & Checkout", ShoppingCart, "Convert gallery visitors into customers.", [
        "Guest checkout",
        "Account checkout",
        "Payment collection",
        "Taxes",
        "Terms acceptance",
        "Order confirmation",
      ]),
      feature("Orders & Invoices", ReceiptText, "Operate the financial side of gallery sales.", [
        "Order management",
        "Invoices and receipts",
        "Refunds",
        "Tax records",
        "Order status",
        "Exportable reports",
      ]),
      feature("Customers", Contact, "Keep a record of gallery buyers and licensees.", [
        "Customer profiles",
        "Organizations",
        "Purchase history",
        "Download history",
        "License history",
        "Customer notes",
      ]),
      feature("Store Analytics", BarChart3, "Measure gallery traffic and commercial performance.", [
        "Visitors and conversion",
        "Product revenue",
        "Asset revenue",
        "Average order value",
        "Top customers",
        "Abandoned carts",
      ]),
    ],
  },
  {
    title: "Licensing",
    icon: BadgeCheck,
    description: "Manage inbound rights and licenses issued to customers.",
    features: [
      feature("Rights Inventory", Scale, "Record the rights the organization owns or controls.", [
        "Rights holders",
        "Acquired rights",
        "Ownership shares",
        "Territories",
        "Channels and media",
        "Rights windows",
      ]),
      feature("License Templates", ScrollText, "Define reusable outbound grants and pricing rules.", [
        "Fixed license templates",
        "Usage types",
        "Territories",
        "Channels",
        "Durations",
        "Restrictions",
      ]),
      feature("License Pricing", CircleDollarSign, "Calculate prices from the requested usage scope.", [
        "Base prices",
        "Territory multipliers",
        "Duration multipliers",
        "Channel multipliers",
        "Exclusivity premiums",
        "Custom quote requests",
      ]),
      feature("Issued Licenses", BadgeCheck, "Track each grant issued to a buyer or licensee.", [
        "Licensee records",
        "Licensed assets and versions",
        "Grant scope",
        "Issue and start dates",
        "License status",
        "License certificate",
      ]),
      feature("Availability & Conflicts", ScanLine, "Prevent licenses that exceed available rights.", [
        "Availability calculation",
        "Territory conflicts",
        "Channel conflicts",
        "Exclusivity conflicts",
        "Rights-window checks",
        "Conflict resolution",
      ]),
      feature("Expirations & Renewals", CalendarClock, "Manage customer-specific license windows.", [
        "Expiration dates",
        "Renewal options",
        "Renewal reminders",
        "Grace periods",
        "Termination",
        "Expired-license actions",
      ]),
      feature("Entitlements & Delivery", FileCheck2, "Control which files a licensee may receive.", [
        "Permitted renditions",
        "Watermarked previews",
        "Secure delivery",
        "Download limits",
        "Entitlement revocation",
        "Delivery evidence",
      ]),
      feature("Releases & Agreements", FileText, "Store releases, contracts, and supporting evidence.", [
        "Model releases",
        "Property releases",
        "Contributor agreements",
        "Signed contracts",
        "Amendments",
        "Consent records",
      ]),
      feature("Revenue & Royalties", CircleDollarSign, "Connect licenses to income and rightsholder obligations.", [
        "Asset-level income",
        "License revenue",
        "Royalty rates",
        "Revenue shares",
        "Minimum guarantees",
        "Recoupment",
      ]),
      feature("Payouts & Statements", Landmark, "Pay rightsholders and explain each calculation.", [
        "Payment schedules",
        "Payout accounts",
        "Royalty statements",
        "Deductions",
        "Payment status",
        "Payout exports",
      ]),
      feature("Usage Reporting", BarChart3, "Collect evidence of licensed usage.", [
        "Licensee usage reports",
        "Placement records",
        "Audience and circulation",
        "Proof of attribution",
        "Usage exceptions",
        "Compliance review",
      ]),
    ],
  },
  {
    title: "Governance",
    icon: ShieldCheck,
    description: "Control access, retention, compliance, and defensible records.",
    features: [
      feature("Permissions", Lock, "Control access from workspace to individual assets.", [
        "Workspace roles",
        "Folder permissions",
        "Collection permissions",
        "Asset permissions",
        "Portal permissions",
        "Field-level permissions",
      ]),
      feature("Identity & Provisioning", UserCheck, "Connect enterprise identity and automate membership.", [
        "Single sign-on",
        "SAML",
        "SCIM",
        "Multi-factor authentication",
        "Domain controls",
        "Automatic deprovisioning",
      ]),
      feature("Rights Restrictions", Scale, "Prevent use that violates rights or policy.", [
        "Usage restrictions",
        "Territory restrictions",
        "Channel restrictions",
        "Embargo dates",
        "Expiration controls",
        "Restricted downloads",
      ]),
      feature("Audit Trail", Activity, "Keep an inspectable record of important actions.", [
        "Immutable event history",
        "Metadata changes",
        "Permission changes",
        "Rights changes",
        "Download evidence",
        "Audit export",
      ]),
      feature("Retention Policies", DatabaseBackup, "Apply lifecycle rules to records and files.", [
        "Retention schedules",
        "Auto-archive",
        "Auto-delete",
        "Policy exceptions",
        "Disposition review",
        "Retention reporting",
      ]),
      feature("Legal Holds", Gavel, "Preserve records subject to legal or regulatory review.", [
        "Hold creation",
        "Asset preservation",
        "Custodian records",
        "Hold notifications",
        "Release from hold",
        "Hold audit history",
      ]),
      feature("Compliance", ShieldAlert, "Manage privacy, accessibility, and content-policy obligations.", [
        "GDPR support",
        "Privacy flags",
        "DMCA takedowns",
        "Accessibility metadata",
        "Consent tracking",
        "Compliance reports",
      ]),
      feature("Security", ShieldCheck, "Protect the application, files, and delivery surfaces.", [
        "Encryption",
        "Malware scanning",
        "Session controls",
        "IP restrictions",
        "Security logs",
        "Enterprise security reviews",
      ]),
    ],
  },
  {
    title: "Intelligence",
    icon: Sparkles,
    description: "Use AI to enrich, discover, moderate, and create content.",
    features: [
      feature("AI Enrichment", Bot, "Generate useful metadata from asset content.", [
        "AI tags",
        "AI captions",
        "AI descriptions",
        "Alt text",
        "Object and scene recognition",
        "Logo recognition",
      ]),
      feature("Semantic Search", ScanSearch, "Retrieve assets by meaning instead of exact keywords.", [
        "Natural-language queries",
        "Semantic ranking",
        "Visual similarity",
        "Reverse image search",
        "Related asset suggestions",
        "Multimodal search",
      ]),
      feature("People & Faces", Contact, "Find people while respecting consent and policy.", [
        "Face detection",
        "Named people",
        "People collections",
        "Consent status",
        "Face-search permissions",
        "Privacy restrictions",
      ]),
      feature("Duplicate Detection", CopyCheck, "Use perceptual analysis to find redundant content.", [
        "Exact duplicates",
        "Near duplicates",
        "Perceptual similarity",
        "Variant grouping",
        "Merge recommendations",
        "Storage savings",
      ]),
      feature("Generative Tools", WandSparkles, "Create and modify assets with governed AI tools.", [
        "Image generation",
        "Generative Fill",
        "Background generation",
        "Image extension",
        "Copy generation",
        "Brand-controlled prompts",
      ]),
      feature("Smart Organization", BrainCircuit, "Recommend structure from content and behavior.", [
        "Category suggestions",
        "Folder suggestions",
        "Collection suggestions",
        "Metadata recommendations",
        "Archive recommendations",
        "Content recommendations",
      ]),
      feature("Content Insights", Gauge, "Surface quality, coverage, and usage opportunities.", [
        "Asset quality scoring",
        "Metadata completeness",
        "Unused content",
        "Content gaps",
        "Performance recommendations",
        "Archive candidates",
      ]),
      feature("AI Moderation", ShieldAlert, "Detect unsafe or disallowed content.", [
        "Safety classification",
        "Policy labels",
        "Sensitive-content detection",
        "Human review queues",
        "Moderation confidence",
        "Decision history",
      ]),
    ],
  },
  {
    title: "Platform",
    icon: Code2,
    description: "Integrate the DAM with creative, business, and developer ecosystems.",
    features: [
      feature("Integrations", Plug, "Connect common creative and business applications.", [
        "Creative tools",
        "Cloud storage",
        "Productivity tools",
        "Project management",
        "Marketing platforms",
        "Social platforms",
      ]),
      feature("CMS & PIM", Database, "Connect assets to content and product records.", [
        "CMS integrations",
        "PIM integrations",
        "Product records",
        "SKU relationships",
        "Publish and unpublish",
        "Content synchronization",
      ]),
      feature("Commerce Connectors", ShoppingCart, "Publish assets and products into commerce systems.", [
        "Ecommerce integrations",
        "Product media sync",
        "Catalog publishing",
        "Storefront asset selection",
        "Variant media",
        "Commerce webhooks",
      ]),
      feature("API", Code2, "Expose assets and operations to custom applications.", [
        "REST API",
        "GraphQL API",
        "Asset CRUD",
        "Search API",
        "Delivery API",
        "Admin API",
      ]),
      feature("SDKs", Package, "Provide supported libraries for application teams.", [
        "JavaScript SDK",
        "TypeScript types",
        "Server SDKs",
        "Upload SDKs",
        "Delivery SDKs",
        "Examples and starters",
      ]),
      feature("Webhooks", Webhook, "Notify external systems when DAM events occur.", [
        "Asset events",
        "Workflow events",
        "Rights events",
        "Order events",
        "Signature verification",
        "Retry and delivery logs",
      ]),
      feature("Developer Platform", PanelTop, "Give developers credentials, logs, and integration controls.", [
        "Application registration",
        "OAuth",
        "API credentials",
        "Scopes",
        "Request logs",
        "Usage limits",
      ]),
      feature("Data Import & Export", FileOutput, "Move metadata and records in standard formats.", [
        "CSV import and export",
        "JSON export",
        "Bulk asset export",
        "Metadata mappings",
        "Migration tools",
        "Scheduled data feeds",
      ]),
    ],
  },
  {
    title: "Analytics",
    icon: BarChart3,
    description: "Measure adoption, content performance, delivery, and revenue.",
    features: [
      feature("Asset Analytics", BarChart3, "Understand how individual assets are found and used.", [
        "Views",
        "Downloads",
        "Shares",
        "Embeds",
        "Usage locations",
        "Performance over time",
      ]),
      feature("Search Analytics", Search, "Improve findability by studying search behavior.", [
        "Top queries",
        "Failed searches",
        "Zero-result queries",
        "Filter usage",
        "Search conversion",
        "Search trends",
      ]),
      feature("Portal Analytics", Globe, "Measure external portal engagement.", [
        "Portal visitors",
        "Popular assets",
        "Downloads",
        "Visitor geography",
        "Referrers",
        "Portal conversion",
      ]),
      feature("Library Health", Gauge, "Monitor quality and operational cleanliness.", [
        "Metadata completeness",
        "Duplicate volume",
        "Expired rights",
        "Unapproved assets",
        "Unused assets",
        "Archive candidates",
      ]),
      feature("Storage & Usage", HardDrive, "Track consumption against plan limits.", [
        "Storage usage",
        "Bandwidth usage",
        "Transformation usage",
        "AI credits",
        "Active users",
        "Limit alerts",
      ]),
      feature("Commerce Analytics", CircleDollarSign, "Track gallery and storefront performance.", [
        "Revenue",
        "Orders",
        "Conversion",
        "Average order value",
        "Product performance",
        "Refunds",
      ]),
      feature("License Analytics", Scale, "Measure the value and risk of issued rights.", [
        "License revenue",
        "Active licenses",
        "Upcoming expirations",
        "Renewal rate",
        "Territory mix",
        "Asset-level licensing income",
      ]),
      feature("Reports & Exports", FileOutput, "Create recurring stakeholder-ready reports.", [
        "Custom dashboards",
        "Scheduled reports",
        "CSV exports",
        "PDF exports",
        "Saved report filters",
        "Report sharing",
      ]),
    ],
  },
];

export const featureNav = featureDomains.map((domain) => ({
  title: domain.title,
  icon: domain.icon,
  description: domain.description,
  subItems: domain.features,
}));

export const featureItems = featureDomains.flatMap((domain) =>
  domain.features.map((item) => ({
    ...item,
    domain: domain.title,
    domainIcon: domain.icon,
  })),
);

export const featureItemsByTitle = new Map(
  featureItems.map((item) => [item.title, item]),
);

export const overviewNavItem = {
  title: "Overview",
  icon: LayoutDashboard,
};
