-- Adopt @geiger/rbac in the assets schema
--
-- geiger-assets is the only product in the suite that never adopted the shared
-- authorization engine: campaign, comms, content and events all own a
-- <schema>.rbac_allows, assets did not. In its place 20260906000000 introduced
-- assets.project_members, gated on role sets hand-copied into lib/storage/auth.js
-- because geiger-rbac.config.js "cannot load server-side". It can — the catalog
-- was throwing at module load on an invalid condition (assets.tip.payout read
-- payout.status off a "tip" resource), so nothing anywhere could import it. The
-- key is now assets.payout.settle and the catalog loads.
--
-- Nothing ever wrote a project_members row, so requireProjectAccess denied every
-- upload, download and delete against a real project. This migration replaces
-- that overlay with the real engine.
--
-- Owns:
--   public.roles                     shared role definitions (suite-wide)
--   assets.role_grants               this product's assignments
--   public.rbac_key_matches(...)     wildcard matching, mirrors keys.js
--   assets.rbac_allows(...)          the predicate RLS policies call
--   assets.rbac_seed_roles(uuid)     seeds the catalog's system roles into a project
--
-- The storage half below is generated by @geiger/rbac's migrationSql("assets") —
-- do not hand-edit it; regenerate from the package if the format changes. Several
-- of its objects (public.roles, rbac_key_matches, rbac_touch_updated_at) already
-- exist from another product's adoption; every statement is guarded so running
-- this second is a no-op on them.
--
-- NOTE ON ENFORCEMENT. This migration creates and populates the authorization
-- tables only. It does NOT replace any product table's `using (true)` demo
-- policy — flipping those is a separate, deliberate migration per table.

-- @up
create extension if not exists pgcrypto;
create schema if not exists assets;
grant usage on schema assets to anon, authenticated, service_role;

-- Shared updated_at trigger for the authorization tables. Declared here (rather
-- than depending on a product's own touch_updated_at) so this block stands alone
-- whichever product runs it first.
create or replace function public.rbac_touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- Wildcard permission matching. Mirrors keys.js: "*" matches everything,
-- "<product>.*" and "<product>.<resource>.*" match by prefix, anything else is
-- an exact match. Immutable so it can be used in an index if that day comes.
create or replace function public.rbac_key_matches(p_patterns text[], p_key text)
returns boolean
language sql
immutable
as $$
  select exists (
    select 1
    from unnest(coalesce(p_patterns, '{}'::text[])) as pat
    where pat = '*'
       or pat = p_key
       or (
         right(pat, 2) = '.*'
         and left(p_key, length(pat) - 1) = left(pat, length(pat) - 1)
       )
  );
$$;

-- Shared role definitions. project_id scopes a role to one workspace; a null
-- project_id is a suite-wide template. permissions[] holds keys and wildcard
-- patterns spanning every product (events.order.refund, flow.issue.close, "*").
create table if not exists public.roles (
  id uuid primary key default gen_random_uuid(),
  project_id uuid references public.projects(id) on delete cascade,
  key text,
  name text not null default 'Untitled role',
  description text not null default '',
  color text not null default 'slate',
  permissions text[] not null default '{}',
  is_system boolean not null default false,
  sort integer not null default 0,
  metadata jsonb not null default '{}'::jsonb,
  created_by uuid,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz
);

alter table public.roles add column if not exists key text;
alter table public.roles add column if not exists permissions text[] not null default '{}';
alter table public.roles add column if not exists metadata jsonb not null default '{}'::jsonb;
alter table public.roles add column if not exists deleted_at timestamptz;

create index if not exists roles_project_idx
  on public.roles (project_id) where deleted_at is null;
create unique index if not exists roles_project_key_uniq
  on public.roles (project_id, key) where key is not null and deleted_at is null;

drop trigger if exists roles_touch_updated_at on public.roles;
create trigger roles_touch_updated_at
before update on public.roles
for each row execute function public.rbac_touch_updated_at();

-- Per-product assignment. One row per (user, role) in a project. scope narrows
-- the grant to specific resources: {"asset": ["<uuid>", ...]}. An empty scope
-- means the grant applies everywhere in the project.
create table if not exists assets.role_grants (
  id uuid primary key default gen_random_uuid(),
  project_id uuid references public.projects(id) on delete cascade,
  user_id uuid not null,
  role_id uuid not null references public.roles(id) on delete cascade,
  scope jsonb not null default '{}'::jsonb,
  status text not null default 'active',
  metadata jsonb not null default '{}'::jsonb,
  granted_by uuid,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz
);

alter table assets.role_grants add column if not exists scope jsonb not null default '{}'::jsonb;
alter table assets.role_grants add column if not exists metadata jsonb not null default '{}'::jsonb;
alter table assets.role_grants add column if not exists deleted_at timestamptz;

-- The lookup rbac_allows() makes on every row of every gated query.
create index if not exists assets_role_grants_lookup_idx
  on assets.role_grants (user_id, project_id) where deleted_at is null;
create index if not exists assets_role_grants_role_idx
  on assets.role_grants (role_id) where deleted_at is null;
create unique index if not exists assets_role_grants_uniq
  on assets.role_grants (project_id, user_id, role_id) where deleted_at is null;

drop trigger if exists role_grants_touch_updated_at on assets.role_grants;
create trigger role_grants_touch_updated_at
before update on assets.role_grants
for each row execute function public.rbac_touch_updated_at();

-- The predicate every gated policy calls.
--
-- SECURITY DEFINER so a user can be authorized by grant rows they cannot
-- themselves select — otherwise the grants table's own RLS would have to be
-- open for authorization to work at all. STABLE so Postgres may cache it within
-- a statement rather than re-running it per row.
--
-- p_scope_type null  -> the permission is unscopeable; grants apply everywhere.
-- grant has no entry for p_scope_type -> that grant is unscoped. (Absence is
-- "no restriction", matching scope.js.)
create or replace function assets.rbac_allows(
  p_permission text,
  p_project uuid default null,
  p_scope_type text default null,
  p_scope_id uuid default null
)
returns boolean
language sql
stable
security definer
set search_path = public, assets
as $$
  select exists (
    select 1
    from assets.role_grants g
    join public.roles r on r.id = g.role_id
    where g.user_id = auth.uid()
      and g.status = 'active'
      and g.deleted_at is null
      and r.deleted_at is null
      and (p_project is null or g.project_id = p_project)
      and public.rbac_key_matches(r.permissions, p_permission)
      and (
        p_scope_type is null
        or not jsonb_exists(g.scope, p_scope_type)
        or (
          p_scope_id is not null
          and jsonb_exists(g.scope -> p_scope_type, p_scope_id::text)
        )
      )
  );
$$;

grant execute on function assets.rbac_allows(text, uuid, text, uuid) to anon, authenticated;
grant execute on function public.rbac_key_matches(text[], text) to anon, authenticated;

alter table public.roles enable row level security;
alter table assets.role_grants enable row level security;

drop policy if exists roles_read on public.roles;
create policy roles_read on public.roles
  for select to anon, authenticated using (deleted_at is null);

drop policy if exists roles_write on public.roles;
create policy roles_write on public.roles
  for all to authenticated using (true) with check (true);

drop policy if exists role_grants_read on assets.role_grants;
create policy role_grants_read on assets.role_grants
  for select to anon, authenticated using (deleted_at is null);

drop policy if exists role_grants_write on assets.role_grants;
create policy role_grants_write on assets.role_grants
  for all to authenticated using (true) with check (true);

-- ---------------------------------------------------------------------------
-- Seed the catalog's system roles into a project.
--
-- Mirrors geiger-rbac.config.js. The app re-seeds on load for projects created
-- later, but doing it here means an existing workspace is authorizable the
-- moment this migration lands rather than on someone's next visit.
--
-- public.roles is SUITE-SHARED and keyed (project_id, key), so a project that
-- already adopted another product owns an "owner"/"member"/... row holding only
-- that product's keys — events seeded ebcc7910's Member with events.* alone.
-- permissions[] is explicitly cross-product ("one role spans products"), so a
-- role that already exists is UNIONED with this catalog's defaults, not skipped:
-- skipping would leave an assets Member without assets.asset.edit and unable to
-- upload, which is the very bug this migration exists to fix.
--
-- The union only ever adds this product's own assets.* keys, so it can neither
-- remove nor widen another product's access. Only is_system rows are updated —
-- a role an administrator re-permissioned through the Permissions & Security
-- screen carries is_system false and is left exactly as they set it.
-- ---------------------------------------------------------------------------
create or replace function assets.rbac_seed_roles(p_project_id uuid)
returns integer
language plpgsql
security definer
set search_path = public, assets
as $$
declare
  v_count integer := 0;
begin
  if p_project_id is null then
    return 0;
  end if;

  create temporary table if not exists _assets_role_seed (
    key text, name text, description text, color text, sort integer, permissions text[]
  ) on commit drop;
  delete from _assets_role_seed;

  insert into _assets_role_seed (key, name, description, color, sort, permissions)
  values
    ('owner', 'Owner', 'Full access to everything, including billing.', 'violet', 0, array['*']::text[]),
    ('admin', 'Admin', 'Manage the workspace, team and roles — no billing control.', 'blue', 1, array['assets.overview.view', 'assets.assets.view', 'assets.media.view', 'assets.collaboration.view', 'assets.workflows.view', 'assets.delivery.view', 'assets.galleries.view', 'assets.memberships.view', 'assets.licensing.view', 'assets.governance.view', 'assets.platform.view', 'assets.analytics.view', 'assets.settings.view', 'assets.membership_tiers.view', 'assets.members.view', 'assets.member_registry.view', 'assets.subscriptions.view', 'assets.recurring_billing.view', 'assets.pay_per_view.view', 'assets.paid_messages.view', 'assets.tips.view', 'assets.payouts.view', 'assets.promo_codes_perks.view', 'assets.access_control.view', 'assets.tier.edit', 'assets.subscription.manage', 'assets.ppv.send', 'assets.message.charge', 'assets.asset.edit', 'assets.asset.delete', 'assets.team.invite', 'assets.team.assign', 'assets.role.manage', 'assets.settings.manage']::text[]),
    ('manager', 'Manager', 'Run memberships and assets; can''t edit roles or billing.', 'emerald', 2, array['assets.overview.view', 'assets.assets.view', 'assets.media.view', 'assets.collaboration.view', 'assets.workflows.view', 'assets.delivery.view', 'assets.galleries.view', 'assets.memberships.view', 'assets.licensing.view', 'assets.governance.view', 'assets.platform.view', 'assets.analytics.view', 'assets.settings.view', 'assets.membership_tiers.view', 'assets.members.view', 'assets.member_registry.view', 'assets.subscriptions.view', 'assets.recurring_billing.view', 'assets.pay_per_view.view', 'assets.paid_messages.view', 'assets.tips.view', 'assets.payouts.view', 'assets.promo_codes_perks.view', 'assets.access_control.view', 'assets.tier.edit', 'assets.subscription.manage', 'assets.ppv.send', 'assets.message.charge', 'assets.asset.edit', 'assets.team.invite', 'assets.team.assign']::text[]),
    ('member', 'Member', 'Day-to-day operational access to the workspace.', 'amber', 3, array['assets.overview.view', 'assets.assets.view', 'assets.memberships.view', 'assets.membership_tiers.view', 'assets.members.view', 'assets.pay_per_view.view', 'assets.analytics.view', 'assets.asset.edit']::text[]),
    ('viewer', 'Viewer', 'Read-only access to the overview and reports.', 'slate', 4, array['assets.overview.view', 'assets.analytics.view']::text[]);

  -- Roles this project does not have yet.
  insert into public.roles (project_id, key, name, description, color, sort, permissions, is_system)
  select p_project_id, s.key, s.name, s.description, s.color, s.sort, s.permissions, true
  from _assets_role_seed s
  where not exists (
    select 1 from public.roles r
     where r.project_id = p_project_id
       and r.key = s.key
       and r.deleted_at is null
  );

  get diagnostics v_count = row_count;

  -- Roles another product already seeded: add this catalog's keys, keep theirs.
  update public.roles r
     set permissions = (
           select array(
             select distinct k
             from unnest(r.permissions || s.permissions) as k
             order by k
           )
         )
    from _assets_role_seed s
   where r.project_id = p_project_id
     and r.key = s.key
     and r.deleted_at is null
     and r.is_system
     and not (r.permissions @> s.permissions);

  return v_count;
end;
$$;

grant execute on function assets.rbac_seed_roles(uuid) to anon, authenticated;

-- Seed every project that exists today.
do $$
declare
  p record;
begin
  for p in select id from public.projects where deleted_at is null loop
    perform assets.rbac_seed_roles(p.id);
  end loop;
end;
$$;

-- @down
-- public.roles, public.rbac_key_matches and public.rbac_touch_updated_at are
-- shared across the suite and are intentionally left in place — rolling this
-- product back must not delete another product's role definitions or break its
-- rbac_allows. The seeded rows are likewise left: they are keyed per project and
-- carry permissions for this product only, and another product's grants may
-- already reference them.
drop function if exists assets.rbac_seed_roles(uuid);
drop policy if exists role_grants_read on assets.role_grants;
drop policy if exists role_grants_write on assets.role_grants;
drop function if exists assets.rbac_allows(text, uuid, text, uuid);
drop table if exists assets.role_grants cascade;
